[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "pip install --no-cache-dir --only-binary=:all: numpy==1.26.4 Pillow==10.3.0",
  "pip install --no-cache-dir -r requirements.txt",
  "pip install --no-cache-dir torch==2.1.0 torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cpu"
]

[start]
cmd = "waitress-serve --port=$PORT app:app"

